### ISSUE TITLE
节点的备注信息出不来

### ISSUE THREAD

**Issue by CipherStronger** [fex-team/kityminder-core#28]
节点添加备注信息后（note），界面图形出现了备注图标（noteIcon），但是鼠标已过去后并没有备注浮标出来。

**Comment by viclyliu** [comment]
我也碰到这个问题，看了源码，没有搞定，大侠帮忙。

**Comment by zhangbobell** [comment]
备注的预览框需要自己做，实现方法可以参考 kityminder-editor

**Comment by laynefyc** [comment]
一个简单的demo，可以参考
1. css
````css
    .mind-content-wrapper{
        display: none;
        border-style: solid;
        white-space: nowrap;
        z-index: 9999999;
        transition: left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s;
        background-color: rgba(245, 245, 245, 0.9);
        border-width: 1px;
        border-color: #0066CC;
        border-radius: 4px;
        color: #000;
        font: 14px/21px "Microsoft YaHei";
        padding: 10px;
        pointer-events: auto;
    }
````
2. 创建一个dom
````html
<div class="mind-content-wrapper" style="position: fixed;" id="content-wrapper"></div>
````

3. js事件监控

````js
var glb_cur = {}; 
km.on('mousemove',function(e,d){
        if(e.getTargetNode() === null){
            $("#content-wrapper").hide();
            return true;
        }

        if(e.getTargetNode().data !==undefined&&e.getTargetNode().data.source!==undefined){
            if(glb_cur === e.getTargetNode().data){
                $("#content-wrapper").show();
                return true;
            }else{
                glb_cur = e.getTargetNode().data;
            }

            $("#content-wrapper").html('');
            var $previewer = $('<div id="note-previewer"></div>').appendTo('#content-wrapper');
            $previewer.hide();
            var note = e.getTargetNode().getData('note');


            $previewer.html(note);


            var x = e.originEvent.pageX + e.getTargetNode().getLayoutBox().width/4;
            var y = e.originEvent.pageY + e.getTargetNode().getLayoutBox().height/4;


            $("#content-wrapper").css({
                left: Math.round(x),
                top: Math.round(y)
            }).show();

            $previewer.show();
            previewLive = true;
        }
    });
````

**Comment by zhaogaolei** [comment]
> 备注的预览框需要自己做，实现方法可以参考 kityminder-editor

## 基于kityminder-editor实现的demo，参考如下：

### css
``` css
#content-wrapper {
      position: fixed;
      display: none;
      background: #FFD;
      padding: 5px 15px;
      border-radius: 5px;
      max-width: 400px;
      max-height: 200px;
      overflow: auto;
      z-index: 10;
      box-shadow: 0 0 15px rgba(0, 0, 0, .5);
      word-break: break-all;
  }
```

### html
```html
 <div id="content-wrapper"></div>
```

### js
```  js
var $container = $("#content-wrapper").parent();
var previewTimer;
km.on('shownoterequest', function (e, d) {
    previewTimer = setTimeout(function () {
        preview(e.node);
    }, 300);
});

km.on('hidenoterequest', function () {
    clearTimeout(previewTimer);
    $("#content-wrapper").hide();
});

function preview(node) {
    var icon = node.getRenderer('NoteIconRenderer').getRenderShape();
    var b = icon.getRenderBox('screen');
    var note = node.getData('note');

    $("#content-wrapper").html('');
    var $previewer = $('<div id="note-previewer"></div>').appendTo('#content-wrapper');
    $previewer.hide();
    $previewer.html(note);


    var cw = $($container[0]).width();
    var ch = $($container[0]).height();
    var pw = $($previewer).outerWidth();
    var ph = $($previewer).outerHeight();

    var x = b.cx - pw / 2 - $container[0].offsetLeft;
    var y = b.bottom + 10 - $container[0].offsetTop;

    if (x < 0) x = 10;
    if (x + pw > cw) {
        x = b.left - pw - $container[0].offsetLeft;
    }
    if (y + ph > ch) {
        y = b.top - ph + 50 - $container[0].offsetTop;
    }

    $("#content-wrapper").css({
        'left': Math.round(x) + 'px',
        'top': Math.round(y) + 'px'
    }).show();

    $previewer.show();
}

```
